name: Samsung SM8150 r5q Kernel Build

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: "Set up build environment"
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc bison flex libssl-dev make libncurses5-dev git curl clang lld \
            libelf-dev erofs-utils android-sdk-libsparse-utils build-essential automake autoconf libtool pkg-config fuse3 e2fsprogs pv liblz4-dev uuid-dev \
            libfuse3-dev fuse3 f2fs-tools fuse2fs attr zlib1g-dev rsync \
            device-tree-compiler lz4 xz-utils zlib1g-dev openjdk-17-jdk gcc g++ python3 python-is-python3 p7zip-full \
            build-essential git libssl-dev bc flex bison \
            libncurses5-dev libncurses-dev cpio zip unzip \
            python3 curl rsync kmod libelf-dev \
            lz4 tar openssl python3-pip \
            gcc clang
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb && sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb             

      - name: "Import kernel source"
        uses: actions/checkout@v4    

      - name: "Setting permission"
        run: chmod +x build.sh

      - name: "Build for specific device"
        run: ./build.sh
